seed: 1
# generate_data: True

net: Predict-TrainedP
data_dir: ../data/flower

tags: [flower-predict, new]

batch_size: 16
max_epochs: 100
lr: 0.01

grid_size: [10, 10]
noise_std: 0.1
y_low: 2
y_high: 7

eps_mult: 0. 1. 1. 1.

n_train: 10000