seed: 42
# generate_data: True

net: TrainImplicitP
hidden_implicit_layers: [49, 49]

# net: TrainP

data_dir: ../data/noise

# Data and transform 
grid_size: [1,7]
noise_std: 1.
eps_mult: 0. 0. 1. 0.

# Training
max_epochs: 100
lr: 0.001

lossweight_o: 1.
# lossweight_dg: 0.
# lossweight_dx: 0.
# lossweight_do: 0.
# lossweight_do_tilde: 1.
# lossweight_do_tilde_mmd: 0.
# lossweight_do_a: 1.
# lossweight_do_b: 0.
# lossweight_do_a_mmd: 0.
# lossweight_do_b_mmd: 0.

batch_size: 16

# criterion: mses

n_train: 10_00

# Logging
tags: [loss, dev]
# logger: None