seed: 42

net: TrainP

data_dir: ../data/noise

# Data and transform 
grid_size: [1,7]
noise_std: 1.

eps_mult: 0. 0. 1. 0.

# Training
max_epochs: 500
lr: 0.001
lossweight_dg: 1
lossweight_o: 1
criterion: mses

n_train: 100000
n_val: 1000
n_test: 1000

# Logging
tags: [loss, dev]

# logger: None

criterion: mses
