seed: 42
net: Predict-CalculatedP

# net: Predict-NoiseTrainedImplicitP
# hidden_implicit_layers: [49, 49]

data_dir: ../data/sine1d
max_epochs: 300

grid_size: [1,7]
noise_std: 0.5
y_low: 1
y_high: 3

eps_mult: 0. 0. 1. 0.


n_train: 1000
n_val: 1000
n_test: 1000

# logger: None
tags: [sine1d-implict-predict, dev]
