#!/bin/bash

#SBATCH --partition=genoa
#SBATCH --gpus=0
#SBATCH --job-name=GenData
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128
#SBATCH --time=00:10:00
#SBATCH --output=jobs/slurm_output/lpsda_generate_data_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/thesis/SymPDE/ext_repos/LPSDA
source activate sympde

srun python -u generate/generate_data.py --experiment=KdV --train_samples=500 --valid_samples=100 --test_samples=100 --L=128 --end_time=50. --suffix=medium